### ISSUE TITLE
Installation back-end: comment demander la validation?

### ISSUE THREAD

**Issue by FlorentChabaud** [LINCnil/pia-back#1]
Bonjour,

Tout d'abord, félicitations pour la première impression du logiciel: très professionnel, et la traduction en anglais, indispensable, est une très agréable surprise.

A fins de test, j'ai installé la version Back-End de PIA. Après avoir renseigné tous les champs, le bouton "Ask for review" ne semble pas s'activer. Si on exporte le projet et qu'on le réimporte en mode local, le bouton s'active. Par contre, il ne semble pas s'activer en mode back-end.

Configuration back-end:
4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Configuration application:
PIA application version 1.1.6 Linux 64 bits
PIA application version 1.1.7 Windows 64 bits

Cordialement,

**Comment by brunto** [comment]
Bonjour,

Tout d'abord je vous remercie pour votre retour positif.
Nous vous ferons un retour très rapidement concernant votre problématique.
Cordialement,

**Comment by brunto** [comment]
Bonjour,
Je n'arrive pas à reproduire.
Pourriez-vous me donner plus de précision et éventuellement un export de votre PIA ?

**Comment by romoloman** [comment]
I confirm this bug too, i have reported the same bug in pia app including the way to reproduce.

**Comment by brunto** [comment]
I think this issue is fixed. I close this ticket.

**Comment by Junark** [comment]
Hi, I installed version 3.2.2 and noticed the same problem, when I click ‘ask for review’ the progress wheel starts to spin and nothing happens, the only section that works is ‘Planned or existing measures’. I thought it was a problem with the installation, however with a test installation on the vbox this problem also occurs. Is there any way to fix this? 
![pia_test](https://github.com/user-attachments/assets/9f71c009-2312-41c6-bd4a-56003015f39a)
