### ISSUE TITLE
Problème à la création des tables 

### ISSUE THREAD

**Issue by Logicsystem360** [LINCnil/pia-back#10]
Bonjour,

J'essaie d'installer PIA sur mon serveur debian mais je parviens pas à créer la base de données quand j'effectue la commande _rake db:migrate_

Voici ce qui sort  : 
== 20170731082629 CreatePias: migrating =======================================
-- create_table(:pias)
   -> 0.0210s
== 20170731082629 CreatePias: migrated (0.0214s) ==============================

== 20170731083917 CreateAnswers: migrating ====================================
-- create_table(:answers)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedObject: ERREUR:  le type « jsonb » n'existe pas
LINE 1: SELECT 'jsonb'::regtype::oid
               ^
: SELECT 'jsonb'::regtype::oid/var/lib/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'

Il y a d'autres lignes mais je suis pas sur de la pertinence, si besoin j'ai copié les lignes.
J'ai eu pas mal de soucis d'installation avec des dépots pas à jour, etc mais là je sèche j'arrive pas à avancer.
Une idée du souci ?

Merci :)

**Comment by brunto** [comment]
Bonjour,
Je pense que votre version de PostgreSQL est trop ancienne.
Le format JSON est disponible à partir de la version 9.3

**Comment by Logicsystem360** [comment]
Merci pour votre réponse.

PostgreSQL est en version 9.6.6 sur mon serveur
Rails 5.0.6
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

**Comment by Logicsystem360** [comment]
Problème réglé, il s'agissait d'une locale de mon debian en euro au lieu de UTF-8
