### ISSUE TITLE
Possibility to use SQL Server?

### ISSUE THREAD

**Issue by djechelon** [LINCnil/pia-back#130]
Hello,

our company fully uses Azure for all services. Might it be possible to install PIA tool on a SQL (Azure) Server database backend.
Postgres is not a total showstopper, yet limiting...

Some info: in order to ensure DB compatibility, scripts should be dialect-neutral, use as least unique features as possible, it is preferred to use an ORM (from the C# world, that's Entity Framework, I don't know about rails). Of course DB creation/migration scripts (DDLs) should be provided twice in the application package.

Thanks

**Comment by brunto** [comment]
Hello,
Maybe this can help https://faun.pub/connecting-a-rails-backend-with-azure-database-for-mysql-d559af6466ba 
Regards

**Comment by brunto** [comment]
Without new information or questions, we allow ourselves to close this issue. Do not hesitate to reopen the issue if necessary.
