### ISSUE TITLE
new installation runbook

### ISSUE THREAD

**Issue by PhilRMCD** [LINCnil/pia-back#140]
Someone here, who is interested to write a new, on latest stable version based installation book? The one that is public now differs from https://github.com/LINCnil/pia-back#installation and that is so confusing.

**Comment by brunto** [comment]
Hello, you can use the wiki, it's up to date for the latest versions: https://github.com/LINCnil/pia-back/wiki

**Comment by brunto** [comment]
Hi, @prazey sorry for the late response. Did you find a solution to customize the UI?
