### ISSUE TITLE
Impossible de connecter le client lourd

### ISSUE THREAD

**Issue by storm83780** [LINCnil/pia-back#148]
Bonjour,
L'installation du back end selon cookbook = OK
La visualisation de la mire pia à partir du navigateur du post client = ok
Mais au moment d'ajouter l'URL du serveur dans le client = connexion impossible.

En mode test, j'ai un message d'erreur qui semble indiquer que le mot de passe de postgre n'est pas fourni?

Started GET "//pias" for 10.242.2.3 at 2021-11-16 19:48:41 +0100
PG::ConnectionBad (fe_sendauth: no password supplied
):
pg (1.2.3) lib/pg.rb:58:in `initialize'
pg (1.2.3) lib/pg.rb:58:in `new'
pg (1.2.3) lib/pg.rb:58:in `connect'

J'ai vérifier mon utilisateur (pia ou pia-user selon les documentations)
J'ai vérifié la configuration de database.yml
Rien n'a faire, impossible de se connecter.
Avez-vous une idée ?
Merci de votre aide.

**Comment by storm83780** [comment]
En attendant, j'ai repris l'installation avec le wiki et cette fois-ci cela fonctionne.
Pour le backoffice = du premier coup
Pour le front, il y a une modification à faire à l'installation de NVM
Installer la version de node 12 en utilisant le manager Nvm source ~/.bashrc && nvm install 12
Il faut utiliser la version 14 maintenant.

Je passe au test de l'outil maintenant (fiabilité, robustesse).
Bonne soirée

**Comment by brunto** [comment]
Bonjour,
Content que vous ayez pu résoudre votre problème.
Je cloture le ticket du coup.
Cordialement
