### ISSUE TITLE
Rpoblème installation

### ISSUE THREAD

**Issue by kifjeff** [LINCnil/pia-back#170]
Bonjour à tous,
J'essaye d'installer l'outil PIA avec ce runbook : https://github.com/LINCnil/pia-back/wiki
Mais je rencontre plusieurs problèmes :

On nous fait installer la version 12 de Node mais avec la commande `yarn install`, la version n'est pas bonne et demande minimum la 14.

On nous fait déplacer un fichier inexistant avec la commande `cp src/environments/environment.prod.ts.example src/environments/environment.prod.ts && yarn prod`

La configuration du nginx pour le pia pointe le root /var/www/pia/dist/pia; alors que j'ai comme dossier uniquement  /var/www/pia/dist/pia-angular

Le fichier nano Gemfile est dejà avec la ligne gem 'dotenv-rails' chez moi.

La configuration du nginx pour le back ne doit pas être bonne, le root est plutôt /var/www/pia-back/public.

Après toutes les modifications je n'ai qu'un message de back qui est bien installé. Des idées sur mon problème ? Quelqu'un à t-il un runbook à jour ?

Merci d'avance 
Jeff

**Comment by brunto** [comment]
Bonjour,
Merci pour ces informations, nous allons vérifier cela.
Nous pouvons vous assister si besoin. Vous pouvez me contacter par email via [mon profil GitHub](https://github.com/brunto)
Bruno

**Comment by kevin-atnos** [comment]
@syl-p il faudrait vérifier ces différents points.

**Comment by syl-p** [comment]
Nous avons eu cette personne en call non @kevin-atnos ? le problème avez été résolu en direct me semble t- il ?

**Comment by kifjeff** [comment]
Non, je suis parti de la société depuis 6 mois donc impossible ;)
