### ISSUE TITLE
Activation code

### ISSUE THREAD

**Issue by info247** [LINCnil/pia-back#191]
Hi

How are additional users added.
Thank you.
![act](https://user-images.githubusercontent.com/3190689/202554760-48c3e329-b8cc-46e6-ac63-4d04c02f83e4.jpg)

**Comment by kevin-atnos** [comment]
Hello @info247,

Do you still have issues with the authentication module?
Did  you find how to create new users? (Users in Settings tab)

Regards,

Kévin

**Comment by info247** [comment]
Hello Kevin

 

Thank you. Its working.

 

Kind regards  Peter
