### ISSUE TITLE
Cannot create admin account

### ISSUE THREAD

**Issue by RobinGremion** [LINCnil/pia-back#193]
Bonjour !
Je suis coincé à l'étape de la création du compte admin (https://github.com/LINCnil/pia-back#create-admin-account).
Je lance la commande comme dans la doc avec mes propres informations
`User.create(email: 'YOUR_EMAIL', password: 'Azeazeaze123-', password_confirmation: 'Azeazeaze123-')`
Puis je sélectionne l'utilisateur créé 
`    a = User.last`
Mais la suite me donne des erreurs :
`a.is_technical_admin = true`
Me donne ceci :
`irb(main):003:0> a.is_technical_admin = true
Traceback (most recent call last):
        1: from (irb):3
NoMethodError (undefined method is_technical_admin= for nil:NilClass)
`
Et toutes les commandes suivantes me donnent une erreur similaire.
Auriez-vous une idée ?
Merci infiniment!

**Comment by syl-p** [comment]
Bonjour @RobinGremion,
Il semble que votre utilisateur ne se soit pas bien créé. Avez vous un retour dans le terminal indiquant bien que votre utilisateur est sauvegarder suite à la commande :

```
User.create(email: 'admin@test.test', password: 'Azeazeaze123-', password_confirmation: 'Azeazeaze123-')
```

? Si il y a un problème avec les informations que vous venez de renseigner le retour commande se terminera par  "TRANSACTION (0.3ms)  ROLLBACK", cela arrive lorsque l'email est déjà utilisé par un autre user ou lorsque le mot de passe n'est pas assez fort ou mal renseigné.

Sinon par un "SAVED" (il me semble)

Ensuite, s'il est bien sauvegardé il devrait ce passer ceci:


```
irb(main):004:0> a = User.last
  User Load (0.3ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<User id: 4, email: "my_user@test.test", created_at: "2022-12-02 16:03:06.311897000 +0000", updated_at: "2022-12-02 16:03:06.311897000 +0000", firstname: nil, lastname: nil, is_technical_admin: false, is_functional_ad...

```

```
irb(main):005:0> a
=> #<User id: 4, email: "my_user@test.test", created_at: "2022-12-02 16:03:06.311897000 +0000", updated_at: "2022-12-02 16:03:06.311897000 +0000", firstname: nil, lastname: nil, is_technical_admin: false, is_functional_admin: false, is_user: false, uuid: "60a0a75a-5f8b-4040-b394-523c34986aa9", login: nil>
```

la suite de la doc, devrait fonctionner.

**Comment by RobinGremion** [comment]
Merci infiniment ! C’était effectivement un souci de mot de passe pas assez fort.
Merci pour l’outil, vous facilitez tellement la vie des juristes qui ont besoin de collaborer sur ce genre de documents

**Comment by RobinGremion** [comment]
Fixed

**Comment by syl-p** [comment]
Avec plaisir @RobinGremion. 
Bonne continuation à vous.
