### ISSUE TITLE
PIA Back V1.6 import bug

### ISSUE THREAD

**Issue by ylachgar** [LINCnil/pia-back#20]
Bonjour,

J'ai installer from scratch la version 1.6 front et back (Ps j'en ai profité pour adapter les images à ma société ;) ).
La version 1.6 front fonctionne correctement avec la version 1.1 du back mais avec la version 1.6 voici les erreurs que j'obtiens : 

A l'import d'un PIA exporter depuis la version front 1.5.0, la creation d'un nouveau PIA ne fonctionne pas également.

![image](https://user-images.githubusercontent.com/35890640/36855024-d48764de-1d72-11e8-86c7-84e2ba745666.png)

Après avoir cliquer sur le bouton "Edit"

![image](https://user-images.githubusercontent.com/35890640/36855056-e782c2a4-1d72-11e8-82c3-886e3e364a63.png)

**Comment by brunto** [comment]
Il est préférable d'utiliser la version 1.6.0 de pia-back pour être cohérent.
Vous pouvez me fournir votre export afin que je puisse voir d'où vient le problème ?

**Comment by brunto** [comment]
Avez-vous réussi à faire fonctionner la version 1.6 front et back ?

**Comment by ylachgar** [comment]
Toujour pas :-/ mais je n'ai pas eu beaucoup de temps pour la troubleshoot.
je vous met un export en attaché
[1520344324839_export_pia_2.zip](https://github.com/LINCnil/pia-back/files/1785231/1520344324839_export_pia_2.zip)

**Comment by ylachgar** [comment]
dsl fausse Manip

**Comment by brunto** [comment]
Bonjour,
Désolé pour la réponse tardive. Je viens de faire le test avec votre export et cela ne pose aucun problème. Après avoir dézippé votre fichier je fais l'import du JSON via le bouton "Importer PIA" et tout fonctionne, j'ai bien accès à votre PIA " TEST -  Code Of Ethics And Compliance"
