### ISSUE TITLE
Docker setup for the PIA-Tool

### ISSUE THREAD

**Issue by kosmas58** [LINCnil/pia-back#21]
Based on [KillianKemps](https://github.com/KillianKemps/pia-back) awesome Docker scripts I've created a separate repository [pia-docker](https://github.com/kosmas58/pia-docker) to generate a complete Docker setup of the PIA application stack on a local machine.

**This setup should be used to evaluate and demonstrate the PIA tool.**

 I'd would be nice, if [LaboCNIL](https://github.com/LINCnil) will take the official ownership of the repository as KillianKemps suggested in  #15. Killian and me can continue to maintain it, if you like. 

The simplicity of the Docker installation would accelerate the spread of the PIA tool in the wild. 

For productive use in a multiuser environment there are still some things missing:

1. First of all - PIA comes without a frontdoor - vulgo authencation. _(I'm already working on that and I'll create a version of the PIA tool including authentication based on devise and omniauth in the backend and Angular token in the frontend. That will be done in three steps 1. create an authentication prototype (that's already done) - 2. add omniauth-ldap for the most common authentication used in business environments - 3. merge that into the PIA application stack)_

2. There is no SSL/TLS encryption of the servers and the communication between them _(but perimeter security is useless without an existing frontdoor and is not needed for access via` localhost` on a local machine)_.

**Comment by bbouille** [comment]
Thank you for this working Docker installation ! It works great on OSx (see https://github.com/LINCnil/pia/issues/142). 

However, please spread the word that Docker set up **is NOT ready for production** grade deployment (no security features at all : no authentification, no database security, no TLS/SSL certificate etc.).

**Comment by kosmas58** [comment]
@bbouille

I've reworked the comment to clarify the purpose of my Docker installation.

In my opinion it was/is obvious, that an installation, that runs based on `localhost`, is not meant for production use in a multiuser environment.

**Comment by SkySymbol** [comment]
Hello,

I'm also working on a docker setup for this tool [over there](https://git.fsfe.org/vincent/pia-docker) and I introduced some kind of authentification [in this commit](https://git.fsfe.org/vincent/pia-docker/commit/886925c55d952233549fcb439c6000a878944ec5). I haven't found a way to authenticate requests between users and the backend though. So I can out this tool in production.

**Comment by bbouille** [comment]
Hello,

Thanks Vincent for this other docker project. Hope to hear quickly from
@LINCnil to manage this feature.

Beside deployment plateforme (Docker or VM or whatever), there is a real
need to implement user authentification and ACL within the PIA apps (front
and back).
I can open a new issue on this topic.

Be careful with production environment, the Basic Auth is definitely not
enough to secure the access (see discussion there :
https://security.stackexchange.com/questions/988/is-basic-auth-secure-if-done-over-https
).
Regarding other security concerns (certificate etc.), some hints might be
provided in the PIA documentation for administrator (yet to initiate).
I would be happy to contribute.

Kind regards,

Benjamin

**Comment by SkySymbol** [comment]
> Be careful with production environment, the Basic Auth is definitely not enough to secure the access

Yes, this is a less-than-optimal solution. Thank you for the advice.

> I would be happy to contribute.

Same, I can help with testing the authentication when it's ready and the documentation.

**Comment by LaboCNIL** [comment]
Hi all,
Kosma and Killian thank you so much for your contribution and making those Docker configurations. We agree with you that a pia-docker repo can be useful. Although, we won't take the ownership of the repo for now. Instead, we can list the Docker repos in the [pia-back readme](https://github.com/LINCnil/pia-back#getting-started). Would that work for you?

**Comment by kosmas58** [comment]
Hi,
that's okay for me. I'll close the issue and maintain to continue my repo.
Kosmas

**Comment by kosmas58** [comment]
@bbouille and @SkySymbol 
the authentication you're discussing doesn't fit to the application stack the PIA tool is using.
The **rails - Angular 2 way** to do it is: devise and omniauth gem in the backend and Angular token in frontend.
Sorry to speak it out clearly, but I'm with rails since 2007. You have to learn the frameworks you are using to build understandable and maintainable software a community can improve and develop.
Regards, 
Kosmas

**Comment by SkySymbol** [comment]
@kosmas58 yes you're absolutely right. The authentication has be done within the application.
I have only talked about these authentication methods as temporary workarounds at the network level because I don't know rails or angular :)

Vincent

**Comment by kosmas58** [comment]
@SkySymbol 
Dear Vincent,

I didn't want to come over as a typical German upper pedantic, but I love the tool and I wanted it to be expanded in a suitable way.

Kosmas

**Comment by SkySymbol** [comment]
No worries :-)
