### ISSUE TITLE
Can't run/install pia-back

### ISSUE THREAD

**Issue by oleksandr-zh** [LINCnil/pia-back#216]
I install your product according to the wiki
I have access to the web interface (successfully installed PIA).
I use NGNX
Completed all Install the Backend (PIA-BACK) steps.
When I try to set up "Server URL Configuration", I have questions:
I have three fields:
Please, provide the address (URL) of the remote server:
ClientID :
Client SECRET :
Wikipedia does not say anything about this (where to get "Client ID" and
"Client SECRET" ?)
Here is what I found:
I ran the command as per https://github.com/LINCnil/pia-back/blob/master/README.md
#############

configure App
Set ENABLE_AUTHENTICATION=true inside your .env file

Enter the rails console with bin/rails c

Launch the command Doorkeeper::Application.create(name: "PIA", redirect_uri: "urn:ietf:wg:oauth:2.0:oob", scopes: ["read", "write"])

Find your UID and SECRET information Doorkeeper::Application.select(:uid, :secret).first

Use these credentials into your PIA application
#####
Here is the result I got on my server:
Doorkeeper::Application.select(:uid, :secret).first
  Doorkeeper::Application Load (0.3ms)  SELECT "oauth_applications"."uid", "oauth_applications"."secret" FROM "oauth_applications" ORDER BY "oauth_applications"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<Doorkeeper::Application:0x00007ff21557dca8 id: nil, uid: "PlhcHp-BlTThNMm12F8_Xn1waiiQ0J8S6GEzaoB_X-Q", secret: "[FILTERED]">

How do i get the secret? (secret: "[FILTERED]")

Tell me, do you have a more accurate manual on how to install this product?

**Comment by kevin-atnos** [comment]
Hello,

Indeed, you need to fill this "Server URL Configuration" form with 3 elements: 
- Your Backend URL ;
- Your client ID ;
- And your client SECRET ;
This way, your Frontend application will link correctly to your Backend application and it will activate the authentication mode.

I have updated the section you are talking about in the README: 
https://github.com/LINCnil/pia-back#configure-app

I agree it wasn't clear. Now you have a better example on how to get your Client ID and Client SECRET.

I hope it will help you complete your installation. Just let me know.

Regards,

**Comment by oleksandr-zh** [comment]
Thank [kevin-atnos](https://github.com/kevin-atnos)

![image](https://github.com/LINCnil/pia-back/assets/50334048/5ae91a3f-c274-47fd-8e05-688550e55f99)

But, i still have error:
![image](https://github.com/LINCnil/pia-back/assets/50334048/69f8dde2-5864-4f4a-90a2-34cc0df3b24f)

![image](https://github.com/LINCnil/pia-back/assets/50334048/e77833b2-dd22-46d9-9733-ccdbe35e8f49)

What am I doing wrong ?

**Comment by oleksandr-zh** [comment]
Thanks for the answer.
When i try login, i see  (authentication.errors.sign_in.404)
![image](https://github.com/LINCnil/pia-back/assets/50334048/aa732af1-050c-422b-bc39-2d46bf9bd223)

and this (console):
![image](https://github.com/LINCnil/pia-back/assets/50334048/00a7fb89-f12e-48e9-b731-2251f53cef7c)

The user is created and permissions granted: 
![image](https://github.com/LINCnil/pia-back/assets/50334048/e6308504-d222-401c-88b5-9a5bfddad000)

**Comment by oleksandr-zh** [comment]
When i use Forgotten link. end enter code, i see next
![image](https://github.com/LINCnil/pia-back/assets/50334048/97916717-36eb-4e44-9d9d-89d19ffe2970)

Then click ""Confirm" ( console):
![image](https://github.com/LINCnil/pia-back/assets/50334048/95088c93-5cec-4002-ac37-29a181d3fbab)


When you try to login with a new password
![image](https://github.com/LINCnil/pia-back/assets/50334048/997cc54e-6d36-4fb4-a42a-a86b72452661)

**Comment by syl-p** [comment]
Helle @oleksandr-zh , what is your pia version and your pia-back version ? I think there is a incompatibility between them.

I think **/oauth/token** it's a route for the latest version (master head) of pia-back.

**Comment by kevin-atnos** [comment]
Hello @oleksandr-zh,

Very strange!
Would you like to have a meeting with us so that we can try to understand better what's going on and also solve your issue?

Can I get your email address so that we can continue by emails please?
Else, you can also join us at contact@atnos.com and we can find a slot to check all of that.

Regards,

Kévin

**Comment by kevin-atnos** [comment]
Hi @oleksandr-zh!

Thank you for joining us in a meeting, we are glad to have solved your issue :)
I will close this issue but if you need any more help you can create another issue on Github here.

For anyone coming here:
The issue was the missing `ENABLE_AUTHENTICATION=true` key missing in the `.env` file.

Regards,
