### ISSUE TITLE
User.create has no effect on the database, no error

### ISSUE THREAD

**Issue by rastaferraille** [LINCnil/pia-back#220]
Hello,

When I folow the wiki explainations, in the rail console using RAILS_ENV=production bin/rails c and User.create method, I recieve a green message but the user is not accessible with User.last method.
Moreover, the database pia_production table users remains empty.

Could you help me with that issue?

Thanks

Bonjour,

Quand je suis les explications du Wiki, en utilisant la console avec la commande  RAILS_ENV=production bin/rails c et la commande User.create, j'ai un message vert comme si tout s'était bien passé.

Pourtant la méthode User.last ne renvoie pas d'objet, et la table users de la base pia_production reste vide...

Merci pour votre aide !

**Comment by rastaferraille** [comment]
Hello,

Sorry, it is resolved : was due to bad password configuration !

Thanks for your work

**Comment by kevin-atnos** [comment]
Hello,

Thank you for your feedback, we are glad you could solve your issue :)
