### ISSUE TITLE
How to enable SSL?

### ISSUE THREAD

**Issue by oleksandr-zh** [LINCnil/pia-back#224]
Hi all. Thank you for your app and your support.
How do I enable HTTPS using an existing certificate?
Here is the config nginx pia-back:
![image](https://github.com/LINCnil/pia-back/assets/50334048/1439661f-d1f5-499a-a6c7-fa2b17557b43)
When I try to log in via HTTPS, I get the following error (I tried to change the rights to the directory/files - this did not fix the error) 
 /var/log/nginx/error.log
2023/06/26 13:37:51 [error] 638781#638781: *197 directory index of "/var/www/pia-back/" is forbidden, client: 192.168.11.100, server: pia.MYDomain.com, request: "GET / HTTP/1.1", host: "pia.MYDomain.com"
![image](https://github.com/LINCnil/pia-back/assets/50334048/4400e056-6ee5-462b-b19f-0e1dbac7a720)

**Comment by brunto** [comment]
Hello @oleksandr-zh you must set the `root` line to `/var/www/pia-back/public`

**Comment by oleksandr-zh** [comment]
Hello. Thank @brunto. But a see stat page only 
![image](https://github.com/LINCnil/pia-back/assets/50334048/e7860a36-7d3f-4bae-9e69-c2cd93dbfddc)

on port 80 I have a fully functional application. I want the same for 443

**Comment by oleksandr-zh** [comment]
When i generate a certificate via Certbot (certbot --nginx -d Mydomain.com) It just adds in /etc/nginx/sites-available/default :
################
listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ Mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ Mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
##############
The app still doesn't work via 443 port

**Comment by brunto** [comment]
Ok, so for that kind of problem, it's more related to a Nginx configuration than the PIA tool.
But we can do a quick meeting to help you. You can contact us at contact@atnos.com to book it.
