### ISSUE TITLE
Ruby 3.2 ?

### ISSUE THREAD

**Issue by busser** [LINCnil/pia-back#233]
La version 3.2 de Ruby est sortie le 25 décembre 2022 et la version 3.3 est imminente.

En lisant la documentation et le code du projet, on dirait que celui-ci n'est compatible qu'avec Ruby 3.1.

Le projet est-il compatible avec Ruby 3.2 ? Si non, que manque-t-il pour y arriver ?

**Comment by kevin-atnos** [comment]
Bonjour,

Vous pouvez utiliser la version 3.2 de Ruby sans aucun souci.

Bien cordialement,
