### ISSUE TITLE
Cant delete activated user from web interface

### ISSUE THREAD

**Issue by ektorasdj** [LINCnil/pia-back#249]
Hello and thank you for this tool.
I have an issue with version 3.2.2
When trying through the front end to delete a user and pressing "Delete this User" the window closes but the user is still there (even after refresh).
I can create and invite new users, and change permissions and Data but not delete them.
A non-activated user can be deleted.
Do you maybe know why?

Thank you

**Comment by ektorasdj** [comment]
Hello,
Problem solved, the user had comments on a pia.
After I deleted them through the rails console (or you can delete the whole pia) the user was deleted successfully.
Thank you!

**Comment by kevin-atnos** [comment]
Hello @ektorasdj,

We are glad that your issue is solved.
It's also interesting to know that there seems to be something a bit off about users and their comments when we want to delete them.
We will investigate this point, thank you for the feedback.

Have a good day!

Regards,
