### ISSUE TITLE
Ajout pièce jointe

### ISSUE THREAD

**Issue by jgrossemy** [LINCnil/pia-back#3]
En environnement de production, l'ajout de pièce jointe ne fonctionne pas.

Trace côté serveur :

>I, [2017-12-01T15:49:56.475785 #29]  INFO -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe] Started POST "/pias/4/attachments" for 10.XX.XX.XX at 2017-12-01 15:49:56 +0000
I, [2017-12-01T15:49:56.477243 #29]  INFO -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe] Processing by AttachmentsController#create as */*
I, [2017-12-01T15:49:56.477410 #29]  INFO -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe]   Parameters: {"attachment"=>{"name"=>"hello world.pdf", "mime_type"=>"application/pdf",
 "pia_id"=>"4", "pia_signed"=>"0", "file"=>"data:;base64,
[...]
U9GCg==", "created_at"=>"Fri Dec 01 2017 16:49:23 GMT+0100 (CET)"}, "pia_id"=>"4"}
D, [2017-12-01T15:49:56.478562 #29] DEBUG -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe]    (0.1ms)  BEGIN
D, [2017-12-01T15:49:56.479827 #29] DEBUG -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe]   Pia Load (0.2ms)  SELECT  "pias".* FROM "pias" WHERE "pias"."id" = $1 LIMIT $2  [["id"
, 4], ["LIMIT", 1]]
D, [2017-12-01T15:49:56.481395 #29] DEBUG -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe]   SQL (0.5ms)  INSERT INTO "attachments" ("pia_id", "created_at", "updated_at") VALUES (
$1, $2, $3) RETURNING "id"  [["pia_id", 4], ["created_at", "2017-12-01 15:49:56.480274"], ["updated_at", "2017-12-01 15:49:56.480274"]]
D, [2017-12-01T15:49:56.503043 #29] DEBUG -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe]    (21.2ms)  COMMIT
I, [2017-12-01T15:49:56.504206 #29]  INFO -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe] [active_model_serializers] Rendered AttachmentSerializer with ActiveModelSerializers::Ad
apter::Attributes (0.38ms)
I, [2017-12-01T15:49:56.504386 #29]  INFO -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe] Completed 500 Internal Server Error in 27ms (ActiveRecord: 21.9ms)
F, [2017-12-01T15:49:56.505141 #29] FATAL -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe]
F, [2017-12-01T15:49:56.505179 #29] FATAL -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe] TypeError (no implicit conversion of nil into String):
F, [2017-12-01T15:49:56.505200 #29] FATAL -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe]
F, [2017-12-01T15:49:56.505239 #29] FATAL -- : [366c98cd-f51f-4976-a0e6-7d7b132b84fe] app/serializers/attachment_serializer.rb:7:in `basename'
[366c98cd-f51f-4976-a0e6-7d7b132b84fe] app/serializers/attachment_serializer.rb:7:in `attached_file'
[366c98cd-f51f-4976-a0e6-7d7b132b84fe] app/controllers/attachments_controller.rb:26:in `create'
>

**Comment by brunto** [comment]
Bonjour,
Ce problème a été identifié et sera corrigé dans la future version qui sera livrée courant semaine prochaine.

**Comment by brunto** [comment]
Au niveau du Backend le problème est corrigé.
Au niveau du Frontend il faut attendre la publication de la prochaine version.
