### ISSUE TITLE
Projet Pia

### ISSUE THREAD

**Issue by segq9pc** [LINCnil/pia-back#30]
Bonjour,
Je viens de finaliser l'installation de Pia en back et en front.

Comment peut on rendre visible tout les projets créés?  à l'ensemble des utlisateurs?
merci

**Comment by benjicolors** [comment]
Bonjour à tous

Merci d'avoir développé ce logiciel, qui nous permettra sans doute d'aider à la mise en place de cette nouvelle réglementation. 

Je rejoins segq9pc, j'ai moi même aussi procédé à l'installation de PIA-BACK & PIA sur un serveur (non sans mal).

Je me suis dis que, comme tout serveur, PIA rendait possible l'accès aux données à l'ensemble des utilisateurs. J'ai donc transmis l'URL tout bêtement à ma collaboratrice pour qu'elle puisse travailler sur le projet avec moi, mais ce n'est pas possible, aucun PIA n'est accessible. 

Pire : je me suis rendu compte qu'un simple vidage du cache du navigateur (partie client) supprimait tous les PIA. On pourrait se poser la question : Est ce que les PIA sont bien stockés dans la base de données SQL ? Ou est-ce le fait de perdre le "cookie" : le système ne reconnaitrait pas l'utilisateur. Bref quoi qu'il en soit, je ne vois pas comment je pourrais récupérer mes PIA si un jour mon HDD de PC tombe en panne.

Je vois mal aussi comment nous pouvons travailler en collaboration avec ce système (étant donné que chaque PIA doit passer entre les mains de plusieurs personnes).

Avez plus d'informations à m'apporter ?

Merci de votre aide

**Comment by brunto** [comment]
Bonjour,
Il semblerai que ce soit un problème avec l'URL. Est-ce que vous mettez bien l'URL avec le http:// ou https:// ?

**Comment by brunto** [comment]
Issue closed due to inactivity
