### ISSUE TITLE
user management, integration with AD

### ISSUE THREAD

**Issue by kotjarka** [LINCnil/pia-back#31]
Hi. thanks for great app. I have questions:
1) It is planned any kind of user management, ability to grant privileges to view/add-edit/accepting PIAs ?
2) It is planned possibility to AD/LDAP integration?

Thanks for your effort.

**Comment by Cyrille37** [comment]
related issue: #72

**Comment by Cyrille37** [comment]
It seems that some work has been done, has show in roadmap "done" column https://github.com/orgs/pia-lab/projects/1#column-2807218

**Comment by brunto** [comment]
@Cyrille37 pia-lab isn't the same project and not related to [the CNIL](https://www.cnil.fr/en/home)

**Comment by kevin-atnos** [comment]
Hello,

The next version (3.1) will have an authentication module with users, roles, profiles and rights management.
This new version should come this autumn 2021.

Thank you,

---

Bonjour,

Pour information, la prochaine version (3.1) contiendra un module de gestion des utilisateurs et de rôles/profils/droits.
Elle devrait arriver pendant l'automne.

Cordialement,
