### ISSUE TITLE
database.yml - unable to set the port

### ISSUE THREAD

**Issue by paolantoni** [LINCnil/pia-back#33]
Considering the template:
development:
  adapter:  postgresql
  host:     myhostname:5632
  encoding: unicode
  database: pia
  pool:     5
  username: piaadmin 
  password: mypassword
  template: template0

is correct to set the port of the cluster in that manner?

Thank you

**Comment by kosmas58** [comment]
Hi there,

a port in `database.yml` is set by `port` for example: `port: 5432`.

Cheers

**Comment by paolantoni** [comment]
Ok I was unsure that adding that field the application was able to read.
