### ISSUE TITLE
 bin/rake db:migrate error `method_missing': undefined method `public_file_server'

### ISSUE THREAD

**Issue by paolantoni** [LINCnil/pia-back#34]
I'm installing Pia in a Debian server. I managed to install all required dependencies (not documented in home page) but i cannot fix this:
piauser@myserver:/var/www/pia/back-end$ RAILS_ENV=production bin/rake db:migrate
/usr/lib/ruby/vendor_ruby/rails/railtie/configuration.rb:95:in `method_missing': undefined method `public_file_server' for #<Rails::Application::Configuration:0x007f2d92bc1cb0>
Did you mean?  public_send (NoMethodError)
        from /var/www/pia/back-end/config/environments/production.rb:19:in `block in <top (required)>'
        from /usr/lib/ruby/vendor_ruby/rails/railtie.rb:210:in `instance_eval'
        from /usr/lib/ruby/vendor_ruby/rails/railtie.rb:210:in `configure'
        from /var/www/pia/back-end/config/environments/production.rb:1:in `<top (required)>'
        from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
        from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:274:in `require'
        from /usr/lib/ruby/vendor_ruby/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
        from /usr/lib/ruby/vendor_ruby/rails/engine.rb:597:in `each'
        from /usr/lib/ruby/vendor_ruby/rails/engine.rb:597:in `block in <class:Engine>'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `each'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `tsort_each_child'
        from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
        from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
        from /usr/lib/ruby/vendor_ruby/rails/application.rb:352:in `initialize!'
        from /var/www/pia/back-end/config/environment.rb:5:in `<top (required)>'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:92:in `require'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:92:in `preload'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:143:in `serve'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:131:in `block in run'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:125:in `loop'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:125:in `run'
        from /usr/lib/ruby/vendor_ruby/spring/application/boot.rb:18:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'

Can you give support?

Debian GNU/Linux 9
sudo bundle install >> OK
sudo gem pristine --all >> OK
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
Rails 5.0.6

Thanks

**Comment by brunto** [comment]
Could you verify if `rails -v ` and `bin/rails -v` return the good version?

**Comment by brunto** [comment]
Issue closed due to inactivity
