### ISSUE TITLE
Cartographie vide en mode pia-back 

### ISSUE THREAD

**Issue by stephnardy** [LINCnil/pia-back#35]
Bonjour

Après installation du serveur pia-back, en utilisant l'application v 1.6.0, la vue "Cartographie des risques" reste vide.
Ce problème n'existe pas avec l'application mode standalone.

Cela vient-il d'un problème de paramétrage du serveur.

En vous remerciant
S. Nardy

**Comment by kosmas58** [comment]
This is a pia issues and reported as  issues #192

**Comment by kevin-atnos** [comment]
Hello,

We have taken into account this problem. We will try to fix it in the next release (beginning of september 2018). If not, it will be fixed in the next release.

Thank you.

**Comment by LaboCNIL** [comment]
Issue solved in [#192](https://github.com/LINCnil/pia/issues/192).
