### ISSUE TITLE
bin/rake db:create

### ISSUE THREAD

**Issue by christophe-lechenadec** [LINCnil/pia-back#4]
Bonjour, 
lors du lancement de la commande
bin/rake db:create
 nous avons l'erreur suivante : 

/var/lib/gems/2.3.0/gems/figaro-1.1.1/lib/figaro/application.rb:64:in `global_configuration': undefined method `reject' for #<String:0x00000003419238> (NoMethodError)
        from /var/lib/gems/2.3.0/gems/figaro-1.1.1/lib/figaro/application.rb:32:in `configuration'
        from /var/lib/gems/2.3.0/gems/figaro-1.1.1/lib/figaro/application.rb:42:in `each'
        from /var/lib/gems/2.3.0/gems/figaro-1.1.1/lib/figaro/application.rb:36:in `load'
        from /var/lib/gems/2.3.0/gems/figaro-1.1.1/lib/figaro.rb:23:in `load'
        from /var/lib/gems/2.3.0/gems/figaro-1.1.1/lib/figaro/rails/railtie.rb:5:in `block in <class:Railtie>'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:49:in `each'
        from /var/lib/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
        from /var/lib/gems/2.3.0/gems/railties-5.0.6/lib/rails/application.rb:90:in `inherited'
        from /opt/pia-back/config/application.rb:20:in `<module:PiaBack>'
        from /opt/pia-back/config/application.rb:19:in `<top (required)>'
        from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
        from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
        from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
        from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
        from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
        from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
        from /var/lib/gems/2.3.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'

Détail de l’Environnement
-- Ubuntu 16.04.3 LTS
-- ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
-- Rails 5.0.6
-- postgresql 9.5
-- Pia-Back
          commit 1b5d2560d68389b81cd5a52b50e35f4ba9eb19d8
          Author: Bruno Perles <bruno@atnos.com>
          Date:   Fri Dec 1 17:48:32 2017 +0100

Cdt,
Ch. Le Chenadec

**Comment by brunto** [comment]
Bonjour
Avez-vous spécifié les variables d'environnement dans le fichier `config/application.yml` ?

**Comment by christophe-lechenadec** [comment]
Bonsoir,

Nous découvrons l’application ainsi que l’environnement Ruby/Rails.
Dans la documentation en ligne et dans le Readme
Il n’est pas question de variables d’environnement.

Juste recopier le fichier  application.example.yml en  application.yml
Et y insérer la SECRET_KEY_HERE

Si vous avez un fichier application type à nous fournir,
Nous sommes preneur.

Cdt,

**Comment by brunto** [comment]
Oui je parle bien de ce fichier, en faite il y a juste besoin de remplacer **__SECRET_KEY_HERE__** par la clé générée via la commande `rake secret`.

**Comment by christophe-lechenadec** [comment]
Bonjour,
nous avons réinstallé le serveur depuis Ruby jusqu’à Postgresql.
Les Commandes de création de base et de migration Fonctionne.

Cdt,
Ch. Le Chenadec
