### ISSUE TITLE
Pia application Menu Tools Absent

### ISSUE THREAD

**Issue by christophe-lechenadec** [LINCnil/pia-back#5]
Bonjour,
nous exécutons  le serveur via la commande
 bin/rails s -b 10.1.8.237 -p 80

=> Booting Puma
=> Rails 5.0.6 application starting in development on http://10.1.8.237:80
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.10.0 (ruby 2.3.1-p112), codename: Russell's Teapot
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://10.1.8.237:80
Use Ctrl-C to stop

Lorsque, depuis un PC on se connecte sur cette URL, nous avons seulement
l'image de fond PIA mais pas de menu Tools.

Ch. Le Chenadec

**Comment by brunto** [comment]
Bonjour,
C'est normal, la version serveur est utilisée uniquement pour l'API REST.
Il vous faut utiliser l'application Front disponible ici : https://github.com/LINCnil/pia-app/releases

**Comment by christophe-lechenadec** [comment]
Désolé, on ne savait qu'il y avait un Client, nous avons eu les infos de manières parcellaires,
nous pensions que l'application était Full Web.

**Comment by brunto** [comment]
En faite, elle peut être aussi "full Web".

Pour le Front vous avez deux solutions : 
1. Utilisez l'application desktop "pia-app" disponible ici : https://github.com/LINCnil/pia-app/releases
2. Installer sur votre serveur l'application Front (accessible via le navigateur) disponible ici : https://github.com/LINCnil/pia/tree/phase1 (Le site étant toujours en version béta je vous encourage à utiliser la branche "phase1")
