### ISSUE TITLE
Running as a service / SystemD service file

### ISSUE THREAD

**Issue by mind-code** [LINCnil/pia-back#53]
I wanted to run pia-back the right way via SystemD and came up with this little service file. I wanted to share it here for others to find or maybe for you to implement it into the project. 

It is tailorded to my personal environment (ruby installed via rvm and a pia user+group for running the app)

**/etc/systemd/system/pia-back.service**
```
[Unit]
Description=Pia Backend
Requires=network.target
Requires=postgresql.service

[Service]
Type=simple
User=pia
Group=pia
WorkingDirectory=/opt/pia/pia-back
Environment=RAILS_ENV=production
ExecStart=/bin/bash -c "source /etc/profile.d/rvm.sh; /opt/pia/pia-back/bin/rails s -b 0.0.0.0 -p 3000"
TimeoutSec=30
RestartSec=15s
Restart=always

[Install]
WantedBy=multi-user.target
```

This works for me, but be sure to adjust it to your particular environment. I give no guarantee for correctness or that this is the best way!

**Comment by sposs** [comment]
Technically, I'm not sure the rails server is made for production. I would at least put a proxy server such as nginx above it.
Or, maybe it could run with Passenger...

**Comment by brunto** [comment]
@sposs You're right, it's better to use Passenger or Puma over Nginx or Apache.
