### ISSUE TITLE
impossible to delete a color declination

### ISSUE THREAD

**Issue by paraillous** [LINCnil/pia-back#58]
I use PrestaShop 1.7.4.3. I would like to remove a color attribute. When I do the manipulation, the color is removed, but when I import CSV, it reappears. I tried to rename it, change the place, empty the caches. Each time, it disappears well and after the import of CSV it reappears. How to make it disappear permanently? Thank you for your help

**Comment by brunto** [comment]
Hi, this is not the repository of prestashop. You can find it here: https://github.com/PrestaShop/PrestaShop
