### ISSUE TITLE
Mise en Production

### ISSUE THREAD

**Issue by christophe-lechenadec** [LINCnil/pia-back#6]
Nous avons rencontrons encore une difficulté,
lors de la mise en oeuvre de l’environnement de PROD nous avons un message d'erreur
avec la commande 
 RAILS_ENV=production rake assets:precompile

celle-ci retourne l'erreur :
rake aborted!
Don't know how to build task 'assets:precompile' (see --tasks)

(See full trace by running task with --trace)

Autre point :
Est-il possible de faire fonctionner le serveur en mode Service (/etc/init.d...)?
Peut-on faire Tourner 2 Environnements (Test et Prod) ?

**Comment by brunto** [comment]
1. Êtes-vous bien dans le répertoire "pia-back" ?
Si oui, pouvez-vous tester avec cette commande : `RAILS_ENV=production bundle exec rake assets:precompile`?

2. Faire fonctionner le serveur en mode Service c'est bien entendu possible. Pour cela il faut installer un serveur APACHE ou NGINX avec le module [Passenger](https://www.phusionpassenger.com/library/install/standalone/install/oss/). (Il y a aussi d'autres solutions : Puma, Unicorn, ...)
Vous pouvez aussi très bien faire tourner 2 environnements, il vous suffit de dupliquer le répertoire "pia-back" et de faire un pointer un service sur l'un et un autre sur l'autre.

**Comment by christophe-lechenadec** [comment]
Oui, nous sommes bien dans le dossier pia-back
j'ai relancé la commande avec l'option --trace
root@vm-pia:/opt/pia-back# RAILS_ENV=production bundle exec rake assets:precompile --trace
rake aborted!
Don't know how to build task 'assets:precompile' (see --tasks)
/var/lib/gems/2.3.0/gems/rake-12.1.0/lib/rake/task_manager.rb:59:in `[]'
/var/lib/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:152:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
/var/lib/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
/var/lib/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:81:in `block in run'
/var/lib/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
/var/lib/gems/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
root@vm-pia:/opt/pia-back#

**Comment by brunto** [comment]
En faite, il n'est pas nécessaire d'effectuer cette opération, c'est une erreur de notre part, je vais retirer cette étape du README. Désolé pour la perte de temps.

**Comment by christophe-lechenadec** [comment]
Pas de Soucis,
L’environnement de test est OK, 
 - démarrage OK
 - saisie de quelques dossier depuis le Client

L’environnement de Prod est également OK
 - Démarrage OK
Les saisies PIA se feront Ultérieurement.

Merci,
Ch. Le Chenadec
