### ISSUE TITLE
pia/pia-back linking issue

### ISSUE THREAD

**Issue by Boulkiess** [LINCnil/pia-back#61]
Hi,

I am having trouble linking the pia app to the pia backend.
I can run both individually, but when I enter the address "http://localhost:3000" in the settings of the app, I get the "connection impossible" error.

The console gives me the following message :
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://localhost:3000/. Raison : l’identification n’est pas prise en charge si la valeur de l’en-tête CORS « Access-Control-Allow-Origin » est « * ».

So I checked in the front-end sources :
fetch(this.settingsForm.value.server_url, {
          mode: 'cors',
          credentials : 'include'
        }

The value include should be what we want indeed but if I understood well the error message in the console, the browser considers this parameter to be "same-origin".

I also checked the backend source:

Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins ENV['ALLOWED_CORS_ORIGINS'].split(',')
    resource '*', headers: :any, methods: %i[get post put patch delete options head]
  end
end

and

ALLOWED_CORS_ORIGINS: '*'

so it should be OK.

Has anyone solved this issue ?

Thanks in advance.

Fabien.

**Comment by brunto** [comment]
Could you try with the community branch. I had to remove the line "credentials: include".
See: https://github.com/LINCnil/pia/commit/b1c2da7e37c762e73c00a2201b19dc974103c6da
