### ISSUE TITLE
NoMethodError: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by kindkains** [LINCnil/pia-back#62]
Hi,

I am trying to install the software pia and using your [Runbook](https://github.com/LINCnil/pia/files/1771633/PIA.Installation.Runbook.V1.2.docx)

Imho this guide is terrible, because the refered versions are too old and a lot of the used commands do not run out of the box and I had to do a lot of research to fix all the problems, but day for day I could find one more solution for the issues, but at the moment I am stuck.

I did
`rake db:create`

and it ran fine.

Afterwards I did

`rake db:migrate`

and I've got an error:

> rake aborted!
> NoMethodError: undefined method `split' for nil:NilClass

To give some more information:

OS: Ubuntu 18.04 LTS (server, no GUI)
ruby: 2.3.1
ruby-rails: 5.0.6
rvm: 1.29.7
rake: 12.3.1-1
gem: 1.1.1
bundler: 2.0.1
nodejs: 8.10.0
Any suggestions what I could do or can I add some additional information for debugging?

[logs.tar.gz](https://github.com/LINCnil/pia/files/3038767/logs.tar.gz)

**Comment by brunto** [comment]
Hi, I htink you don't have the file config/application.yml
Did you do this step ? https://github.com/LINCnil/pia-back#create-and-fill-the-file-applicationyml

**Comment by kindkains** [comment]
Thank you for your answer.
Yes, I did this step.
In this file (/opt/pia-back/config/application.yml) is only one line

`SECRET_KEY_BASE: abbf82.........`

**Comment by brunto** [comment]
Ok you must add the second line: https://github.com/LINCnil/pia-back/blob/master/config/application.example.yml#L2

**Comment by kindkains** [comment]
That's it!
Thank you very much, it's working now!

This line is missing in the run book.

**Comment by mdeweerd** [comment]
Même problème ici, même solution - le runbook est à mettre à jour (versions, etc).

**Comment by simrankumari3010** [comment]
> Thank you for your answer. Yes, I did this step. In this file (/opt/pia-back/config/application.yml) is only one line
> 
> `SECRET_KEY_BASE: abbf82.........`

Can you please tell me this 2 commands

**Comment by brunto** [comment]
@simrankumari3010 Since 2019 we moved from the "Figaro" gem to the "dotenv-rails" gem.
In which version of pia-back are you?
Depending on your version you must set https://github.com/LINCnil/pia-back/blob/master/.env-example instead.

By the way, to generate the SECRET_KEY_BASE you must run `bundle exec rake secret`
