### ISSUE TITLE
Travail collaboratif

### ISSUE THREAD

**Issue by infoifop** [LINCnil/pia-back#65]
Bonjour,

Nous avons mis en place PIA-back sur notre environnement.
Grâce à la documentation d'installation, nous avons réalisés l'installation sans trop de difficultés. Actuellement, les fiches PIA sont stockées sur le navigateur et il n'est donc pas possible de visionner ou de modifier ces fiches par un autre utilisateur / autre ordinateur sans passer par un export.
Serait-ce une erreur lors de l'installation ou est-ce une fonctionnalité qui n'est pour l'instant pas disponible ?

Merci d'avance pour vos retours

**Comment by kevin-atnos** [comment]
Bonjour,

Lorsque votre serveur PIA back est lancé, il faut indiquer son adresse dans l'application PIA front.
Cela se trouve au niveau du menu `"Outils -> Paramètres"` où il est possible d'indiquer l'adresse du serveur concerné.

Avez-vous pu prendre connaissance de la section `"Run the application"` disponible sur le Git de `pia-back` ? Les différentes instructions y sont détaillées afin de connecter le front avec le back : https://github.com/LINCnil/pia-back#run-the-application

Cordialement,

**Comment by infoifop** [comment]
Tout d'abord, merci de votre retour rapide.

Lorsque je renseigne l'adresse du serveur PIA Back sur l'application PIA Front, la connexion est impossible.
Pour tester j'ai fais un `wget localhost:3000` sur le serveur PIA Back en mode Dev, la connexion se fait mais en mode Prod j'ai une connexion refusée.
J'avais accès au back en prod sur mon navigateur Web lors de mes derniers tests mais impossible aujourd'hui.

Cordialement,

**Comment by brunto** [comment]
Bonjour,
Est-ce que vous spécifiez bien l'URL comme ceci : `http://localhost:3000` ?

**Comment by infoifop** [comment]
Bonjour,
Oui mais lorsque je valide il est dit que la connexion est impossible

**Comment by brunto** [comment]
Je peux vous proposer de faire un partage d'écran afin de voir si je peux vous aider à résoudre cela.

**Comment by infoifop** [comment]
Bonjour,
Seriez-vous disponible aujourd'hui ?
Je reste a votre disposition pour toute information complémentaire.

Cordialement,

**Comment by brunto** [comment]
Oui, vous pouvez me contacter directement par email.
Celui-ci est présent ici : https://github.com/brunto
