### ISSUE TITLE
Duplicate entry in "Fundamental principles" view ("Action plan" view)

### ISSUE THREAD

**Issue by yvesb** [LINCnil/pia-back#68]
First of all, thank you for making this tool available to the community.

I want to report a duplicate entry in "Fundamental principles" view:
- "Information des personnes" appears twice (second one should be " Droit d'accès et droit à la portabilité" instead)
- True in FR and EN version (no further language test)
- Action to reproduce: appears irrespective of - desktop or server - version including plain vanilla install without any user input (i.e. this is visible on example project)
- Version tested : V2.0.0 both desktop (Win and Mac OS) and server version (using Yunohost install https://github.com/YunoHost-Apps/pia_ynh on Debain Stretch )
- Browser  : FF 65.0.5 (64b) for server version (client connection side)
- OS : Win 10 64b 

![Information des personnes](https://user-images.githubusercontent.com/760771/57985425-366fe100-7a68-11e9-9720-5250c7efbbab.PNG)

**Comment by brunto** [comment]
Thx for your report. This is fixed in https://github.com/LINCnil/pia/commit/6653650f7390b18815c3e6a9b4f6f12e3902513e#diff-758d9a73a7c5731cd694972569bdb2ea
