### ISSUE TITLE
probleme installation

### ISSUE THREAD

**Issue by dufour59700** [LINCnil/pia-back#7]
Bonjour,
Je voudrai installer la version web du PIA mais je bloque .
J'ai installé ruby rails et postgresql + modifié les fichiers ensuite j'ai fait l'install du bundle sans erreur

Mais quand je lance le db:create (nothing!! ) donc je cherche de l'aide en plus je suis novice sur ubuntu donc désolé;)
*****--- voila mon probleme il ne crée rien dans postgresql----**************************
root@dufour-Virtual-Machine:/home/dufour/pia-back# bin/rake db:create
/home/dufour/pia-back/config/environments/development.rb:46:in `block in <top (required)>': uninitialized constant ActiveSupport::EventedFileUpdateChecker (NameError)
	from /usr/lib/ruby/vendor_ruby/rails/railtie.rb:210:in `instance_eval'
	from /usr/lib/ruby/vendor_ruby/rails/railtie.rb:210:in `configure'
	from /home/dufour/pia-back/config/environments/development.rb:1:in `<top (required)>'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:597:in `each'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:597:in `block in <class:Engine>'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `each'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
	from /usr/lib/ruby/vendor_ruby/rails/application.rb:352:in `initialize!'
	from /home/dufour/pia-back/config/environment.rb:5:in `<top (required)>'
	from /usr/lib/ruby/vendor_ruby/spring/application.rb:92:in `require'
	from /usr/lib/ruby/vendor_ruby/spring/application.rb:92:in `preload'
	from /usr/lib/ruby/vendor_ruby/spring/application.rb:143:in `serve'
	from /usr/lib/ruby/vendor_ruby/spring/application.rb:131:in `block in run'
	from /usr/lib/ruby/vendor_ruby/spring/application.rb:125:in `loop'
	from /usr/lib/ruby/vendor_ruby/spring/application.rb:125:in `run'
	from /usr/lib/ruby/vendor_ruby/spring/application/boot.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
root@dufour-Virtual-Machine:/home/dufour/pia-back# 
****************-------------------------------------------------*****************************************************

Merci pour votre aide

Sincerement  a+

**Comment by brunto** [comment]
Bonjour,
Avez-vous remplit le fichier `config/database.yml` ?

**Comment by jagogordonne** [comment]
Bonjour @brunto ,

Le fichier `config/database.yml` est bien renseigné.
J' obtiens le même message d'erreur que @dufour59700 

`Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch
`

Merci

**Comment by brunto** [comment]
Il faudrait vérifier si vous arrivez à vous connecter à la base de données en console.

**Comment by jagogordonne** [comment]
Bonjour,

La connexion se fait sans problème :
`root@****:/var/www/html/pia.*****.com/pia-back# psql -h 192.168.*.* test-PIA postgres
Mot de passe pour l'utilisateur postgres :
psql (9.6.6)
Connexion SSL (protocole : TLSv1.2, chiffrement : ECDHE-RSA-AES256-GCM-SHA384, bits : 256, compression : désactivé)
Saisissez « help » pour l'aide.

test-PIA=#`

Résultat :
`root@**:/var/www/html/pia.**.com/pia-back# bundle exec bin/rake db:create
root@**:/var/www/html/pia.**.com/pia-back# /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:40:in `block in setup': You have already activated bundler 1.16.1, but your Gemfile requires bundler 1.13.6. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:25:in `map'
        from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:25:in `setup'
        from /usr/lib/ruby/vendor_ruby/bundler.rb:99:in `setup'
        from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:10:in `<top (required)>'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/vendor_ruby/spring/commands.rb:33:in `<module:Spring>'
        from /usr/lib/ruby/vendor_ruby/spring/commands.rb:4:in `<top (required)>'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:77:in `preload'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:143:in `serve'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:131:in `block in run'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:125:in `loop'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:125:in `run'
        from /usr/lib/ruby/vendor_ruby/spring/application/boot.rb:18:in `<top (required)>'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from -e:1:in `<main>'
`

Peut-être la version du bundler ?

Autre action essayé : `bundle update rake`

Merci pour l'aide.
Cordialement

**Comment by brunto** [comment]
Essayez : 
```
gem install bundler
bundle install
bundle exec rake db:create
```

**Comment by jagogordonne** [comment]
OK super les bases et les tables sont créés.

**Comment by dufour59700** [comment]
Moi aussi bases et tables crées

Cordialement


[image: Message ecologie signature email 1]

2018-01-09 14:26 GMT+01:00 jagogordonne <notifications@github.com>:

**Comment by brunto** [comment]
Content d'apprendre que tout fonctionne.
