### ISSUE TITLE
Version plus recente de la documentation

### ISSUE THREAD

**Issue by lrasoanaivo** [LINCnil/pia-back#70]
Bonjour , 
Avez vous une version plus recente de la documentation "Installation.Runbook.V1.2.dox" sur Ubuntu 18.4 car je bloque déja  sur l' etape 5 .2 
bundle install .

1- Avec ruby 2.3.1 , j'ai l'erreur suivante 
Your Ruby version is 2.3.1, but your Gemfile specified ~> 2.5.5

2- J'ai mis la version de ruby 2.5.5 , j'ai les erreurs suivantes
Traceback (most recent call last):
        4: from /usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
        3: from /usr/local/rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
        2: from /usr/local/rvm/gems/ruby-2.5.5/bin/bundle:23:in `<main>'
        1: from /usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/local/rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>=                        0.a) with executable bundle (Gem::GemNotFoundException)
Merci pour votre aide
Lanto R.

**Comment by brunto** [comment]
Bonjour,
Nous allons mettre à jour le Runbook prochainement.

**Comment by brunto** [comment]
Bonjour, nous avons centralisé toutes les informations des divers contributeurs dans le wiki : https://github.com/LINCnil/pia-back/wiki
