### ISSUE TITLE
Récupération d'un PIA supprimé par erreur

### ISSUE THREAD

**Issue by kinsk** [LINCnil/pia-back#73]
Bonjour, est-il possible de récupérer un PIA supprimer par erreur ?
Les données sont-elles conservées dans la base en cas de suppression ?

Merci.

**Comment by brunto** [comment]
Bonjour,
Non si vous avez supprimé le PIA via le bouton "supprimer" présent sur chaque fiche de PIA alors il est supprimé définitivement. Nous prévoyons de rajouter une fonctionnalité d'archivage dans une prochaine version.
