### ISSUE TITLE
Installation sur Windows Serveur 2012 R2

### ISSUE THREAD

**Issue by Angond** [LINCnil/pia-back#8]
Bonjour,

J'aimerais savoir si il est possible d'avoir un tutoriel plus axé sur les systèmes Windows notamment serveurs 2012 R2.

En effet lors de l'installation sur une VM de test en suivant les étapes nous arrivons à accéder à la partie "Test" (le ligi PIA s'affiche simplement) mais lorsque nous démarrons en mode "production" nous avons un message d'erreur "Missing secret_key_base for 'production' environment, set this value in config/secrets.yml".

Je précise que nous avons bien généré la clé avec le rake secret, copié cette dernière dans le fichier application.yml mais malgré tout rien n'y fait. (normalement si je ne me trompe pas le fichier secrets.yml récupère pour l'environnement de production la valeur contenu dans le fichier application.yml)

Merci d'avance pour votre aide.

Cordialement.

**Comment by iouss** [comment]
Bonjour,
Pour ma part ça fonctionne sur un Windows Serveur 2012 r2, il faut générer la clé rake secret depuis le répertoire /bin et n'oubliez pas de mettre a jour le fichier database.yml ( il faut respecter l'espace entre la variable et la valeur ) 
mnt je suis bloqué sur la partie Front

**Comment by brunto** [comment]
Bonjour,
Je clôture ce ticket, si vous avez besoin d'aide pour le front c'est par ici : https://github.com/LINCnil/pia/issues
