### ISSUE TITLE
ruby version

### ISSUE THREAD

**Issue by dercolano-pccube** [LINCnil/pia-back#80]
Gem::InstallError: spring requires Ruby version >= 2.4.0.
An error occurred while installing spring (2.1.0), and Bundler cannot continue.
Make sure that `gem install spring -v '2.1.0' --source 'https://rubygems.org/'` succeeds before bundling.

Requirements and runbook talk abount Ruby v2.3.1, which is the correct one?

**Comment by brunto** [comment]
Hello,
The runbook is for a previous version of pia-back.
You need at least the version 2.5.5 of ruby https://github.com/LINCnil/pia-back/blob/master/Gemfile#L8

**Comment by dercolano-pccube** [comment]
Hello and thank you very much indeed for your kind reply.
What about the other software versions?
Ruby 2.5.5
Rails 5.0.x ??
PostgreSQL 9.4+ ?? (Any test on PostgreSQL 12?)

**Comment by brunto** [comment]
When you `bundle install` all the gems are installed with the good version.
You can check all versions in the Gemfile: https://github.com/LINCnil/pia-back/blob/master/Gemfile and the Gemfile.lock: https://github.com/LINCnil/pia-back/blob/master/Gemfile.lock
About PostgreSQL, it works on 9.4 and probably higher.

**Comment by brunto** [comment]
The README is updated.
