### ISSUE TITLE
Import doesn't work

### ISSUE THREAD

**Issue by Jawor13** [LINCnil/pia-back#99]
I want to import a file created in the pia-app by my frien and I have got the attached error.

![PIA_erro](https://user-images.githubusercontent.com/70325788/91440476-f3a5d700-e86e-11ea-8faf-e964ff545d75.PNG)

**Comment by brunto** [comment]
Hello,
Could you send me the file by email bruno@atnos.com? I'll try to import it on my computer and find a way to fix the problem.

**Comment by Jawor13** [comment]
I got a .json file instead .pia and it works properly. So I close my ticket.
